/**
 * Real, build-time Tailwind config -- a direct translation of the JS
 * object that used to be assigned to `tailwind.config` inside the
 * cdn.tailwindcss.com runtime-JIT script in app/layout.js. Nothing here is
 * new; every key matches that config exactly, so switching to a compiled
 * build shouldn't change what any class actually renders as.
 *
 * @type {import('tailwindcss').Config}
 */
module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{js,jsx}", "./components/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "rgb(var(--color-on-secondary-container-rgb) / <alpha-value>)",
        "secondary-fixed": "rgb(var(--color-secondary-fixed-rgb) / <alpha-value>)",
        "surface-variant": "rgb(var(--color-surface-variant-rgb) / <alpha-value>)",
        "on-primary-fixed-variant": "rgb(var(--color-on-primary-fixed-variant-rgb) / <alpha-value>)",
        "surface-container": "rgb(var(--color-surface-container-rgb) / <alpha-value>)",
        "on-primary-fixed": "rgb(var(--color-on-primary-fixed-rgb) / <alpha-value>)",
        "inverse-surface": "rgb(var(--color-inverse-surface-rgb) / <alpha-value>)",
        "tertiary-container": "rgb(var(--color-tertiary-container-rgb) / <alpha-value>)",
        "on-background": "rgb(var(--color-on-background-rgb) / <alpha-value>)",
        "tertiary-fixed-dim": "rgb(var(--color-tertiary-fixed-dim-rgb) / <alpha-value>)",
        "on-primary": "rgb(var(--color-on-primary-rgb) / <alpha-value>)",
        "surface-tint": "rgb(var(--color-surface-tint-rgb) / <alpha-value>)",
        secondary: "rgb(var(--color-secondary-rgb) / <alpha-value>)",
        "primary-fixed-dim": "rgb(var(--color-primary-fixed-dim-rgb) / <alpha-value>)",
        "surface-dim": "rgb(var(--color-surface-dim-rgb) / <alpha-value>)",
        outline: "rgb(var(--color-outline-rgb) / <alpha-value>)",
        "on-error-container": "rgb(var(--color-on-error-container-rgb) / <alpha-value>)",
        "surface-container-lowest": "rgb(var(--color-surface-container-lowest-rgb) / <alpha-value>)",
        "on-secondary-fixed": "rgb(var(--color-on-secondary-fixed-rgb) / <alpha-value>)",
        "surface-bright": "rgb(var(--color-surface-bright-rgb) / <alpha-value>)",
        "on-tertiary": "rgb(var(--color-on-tertiary-rgb) / <alpha-value>)",
        "on-tertiary-container": "rgb(var(--color-on-tertiary-container-rgb) / <alpha-value>)",
        "on-primary-container": "rgb(var(--color-on-primary-container-rgb) / <alpha-value>)",
        "secondary-container": "rgb(var(--color-secondary-container-rgb) / <alpha-value>)",
        error: "rgb(var(--color-error-rgb) / <alpha-value>)",
        "primary-container": "rgb(var(--color-primary-container-rgb) / <alpha-value>)",
        "on-tertiary-fixed": "rgb(var(--color-on-tertiary-fixed-rgb) / <alpha-value>)",
        "on-secondary": "rgb(var(--color-on-secondary-rgb) / <alpha-value>)",
        "tertiary-fixed": "rgb(var(--color-tertiary-fixed-rgb) / <alpha-value>)",
        "secondary-fixed-dim": "rgb(var(--color-secondary-fixed-dim-rgb) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--color-on-surface-variant-rgb) / <alpha-value>)",
        "surface-container-high": "rgb(var(--color-surface-container-high-rgb) / <alpha-value>)",
        "on-surface": "rgb(var(--color-on-surface-rgb) / <alpha-value>)",
        background: "rgb(var(--color-background-rgb) / <alpha-value>)",
        "on-secondary-fixed-variant": "rgb(var(--color-on-secondary-fixed-variant-rgb) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--color-surface-container-highest-rgb) / <alpha-value>)",
        "inverse-primary": "rgb(var(--color-inverse-primary-rgb) / <alpha-value>)",
        "error-container": "rgb(var(--color-error-container-rgb) / <alpha-value>)",
        "outline-variant": "rgb(var(--color-outline-variant-rgb) / <alpha-value>)",
        tertiary: "rgb(var(--color-tertiary-rgb) / <alpha-value>)",
        primary: "rgb(var(--color-primary-rgb) / <alpha-value>)",
        "on-tertiary-fixed-variant": "rgb(var(--color-on-tertiary-fixed-variant-rgb) / <alpha-value>)",
        surface: "rgb(var(--color-surface-rgb) / <alpha-value>)",
        "on-error": "rgb(var(--color-on-error-rgb) / <alpha-value>)",
        "inverse-on-surface": "rgb(var(--color-inverse-on-surface-rgb) / <alpha-value>)",
        "primary-fixed": "rgb(var(--color-primary-fixed-rgb) / <alpha-value>)",
        "surface-container-low": "rgb(var(--color-surface-container-low-rgb) / <alpha-value>)",
        accent: "#6A2BC2",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "1rem",
        xl: "0.625rem",
        full: "9999px",
      },
      gridTemplateColumns: {
        20: "repeat(20, minmax(0, 1fr))",
      },
      spacing: {
        gutter: "24px",
        "stack-sm": "8px",
        "stack-xs": "4px",
        "margin-mobile": "16px",
        "stack-lg": "24px",
        "container-max": "1440px",
        "stack-xl": "48px",
        "margin-desktop": "40px",
        unit: "4px",
        "stack-md": "16px",
      },
      fontFamily: {
        "label-md": ["var(--font-dm-sans)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-dm-sans)", "sans-serif"],
        "body-md": ["var(--font-dm-sans)", "sans-serif"],
        "code-sm": ["var(--font-jetbrains-mono)", "monospace"],
        "headline-lg": ["var(--font-dm-sans)", "sans-serif"],
        "body-lg": ["var(--font-dm-sans)", "sans-serif"],
        display: ["var(--font-dm-sans)", "sans-serif"],
        "headline-md": ["var(--font-dm-sans)", "sans-serif"],
        "body-sm": ["var(--font-dm-sans)", "sans-serif"],
        script: ["var(--font-caveat)", "cursive"],
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "15px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-lg-mobile": ["21px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "code-sm": ["12px", { lineHeight: "17px", fontWeight: "400" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "25px", fontWeight: "400" }],
        display: ["44px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-md": ["21px", { lineHeight: "28px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
